version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: Lab_04_Semenyshyn_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017 
    depends_on:
      - db

volumes:
  mongo_data: